### ISSUE TITLE
AttributeError: \'Network\' object has no attribute \'proxy\'' in network.py

### ISSUE THREAD

**Issue by letozaf** [lbryio/lbryum#128]
I installed lbryum on Ubuntu 17.04 amd64 Desktop with:

```
$ git clone https://github.com/lbryio/lbryum
$ cd lbryum
$ virtualenv mylbryum
$ source mylbryum/bin/activate
$ pip install -r requirements.txt
$ pip install -e .
$ lbryum daemon start
```

Launching `lbryum daemon status` returns this output/error:

$ lbryum daemon status
Traceback (most recent call last):
  File "/home/carla/Documents/lbryum/mylbryum/bin/lbryum", line 11, in <module>
    load_entry_point('lbryum', 'console_scripts', 'lbryum')()
  File "/home/carla/Documents/lbryum/lbryum/main.py", line 242, in main
    result = server.daemon(config_options)
  File "/home/carla/Documents/lbryum/mylbryum/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 288, in __call__
    return self.__send(self.__name, args)
  File "/home/carla/Documents/lbryum/mylbryum/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "/home/carla/Documents/lbryum/mylbryum/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/home/carla/Documents/lbryum/lbryum/network.py", line 304, in get_parameters | AttributeError: \'Network\' object has no attribute \'proxy\'')

**Comment by jackrobison** [comment]
👍 These are great, please find more broken commands!
