### ISSUE TITLE
AttributeError: \'module\' object has no attribute \'LBRYUM_VERSION\'' in commands.py

### ISSUE THREAD

**Issue by letozaf** [lbryio/lbryum#129]
I installed lbryum on  Ubuntu 17.04 amd64 Desktop with:
```
$ git clone https://github.com/lbryio/lbryum
$ cd lbryum
$ virtualenv mylbryum
$ source mylbryum/bin/activate
$ pip install -r requirements.txt
$ pip install -e .
$ lbryum daemon start
```

Launching lbryum version returns this output/error:

$ lbryum version
Traceback (most recent call last):
  File "/home/carla/Documents/lbryum/mylbryum/bin/lbryum", line 11, in <module>
    load_entry_point('lbryum', 'console_scripts', 'lbryum')()
  File "/home/carla/Documents/lbryum/lbryum/main.py", line 273, in main
    result = server.run_cmdline(config_options)
  File "/home/carla/Documents/lbryum/mylbryum/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 288, in __call__
    return self.__send(self.__name, args)
  File "/home/carla/Documents/lbryum/mylbryum/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "/home/carla/Documents/lbryum/mylbryum/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/home/carla/Documents/lbryum/lbryum/commands.py", line 404, in version | AttributeError: \'module\' object has no attribute \'LBRYUM_VERSION\'')

**Comment by elopio** [comment]
Happens to me too, in ubuntu 16.04, installing with:

```
$ git clone https://github.com/lbryio/lbryum
$ sudo apt install python-virtualenv
$ python -m virtualenv --python=python2 .env
$ pip install -r requirements.txt
$ pip install .
```

**Comment by jackrobison** [comment]
Do other commands work? `lbryum help`

https://github.com/lbryio/lbryum/pull/131 fixes the `version` command, which was indeed broken
