### ISSUE TITLE
Cannot edit claim that has a tip/support - "cannot update a support"

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbryum#160]
Error from here: https://github.com/lbryio/lbryum/blob/766c48826514dd932d688ff13c18d30c0ad3a28f/lbryum/commands.py#L1914

User @oakey22 noticed this when trying to edit his publish on lbry://one. On 10/11 he was able to edit his published file and then tried again on 10/12 and it would not work. The daemon would show "Cannot update a support".   

When I tried to reproduce it, I was initially able to edit an older claim that has supports on it. Then I added some more and I was able to reproduce the issue.  I then created a new claim, added support and also able to recreate the issue. I'm not sure what the exact combination of factors is, but it seems that LBRY gets confused about some UXTOs revolving around supports. 

Original publish: 
```
2017-10-13 12:36:22,418 INFO     lbrynet.daemon.Daemon:1908: Publish: {'claim_address': None, 'name': u'support1', 'bid': 0.01, 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'version': '_0_0_1', 'metadata': {u'description': u'original claim', u'license': u'', u'title': u'support issue', u'language': u'en', 'version': '_0_1_0', u'nsfw': False, u'licenseUrl': None}}}, 'file_path': u'C:\\Users\\SoloDolo\\Desktop\\curl.exe', 'change_address': None}
2017-10-13 12:36:22,420 INFO     lbrynet.daemon.Publisher:27: Starting publish for support1
2017-10-13 12:36:22,599 INFO     lbrynet.lbry_file.EncryptedFileMetadataManager:246: Saved sd blob hash 5bec71ad464d86ddf29d8858b9a159d2552bb8cd0d15eb1fa5aee64013c6e2af81a99d5b12586471a56f344e4d5ed468 to stream hash a2051028ffc1b764000bea4cf92cb2e30921a875a7bc5a1f1cc36fdb0fb70a60384eb927bd2f0689ec0fb21cc02dce6b
2017-10-13 12:36:22,602 INFO     lbrynet.core.Wallet:1368: Send claim: support1 for 0.01: 080110011a85010801122f080410011a0d737570706f7274206973737565220e6f726967696e616c20636c61696d2a00320038004a0052005a001a50080110011a305bec71ad464d86ddf29d8858b9a159d2552bb8cd0d15eb1fa5aee64013c6e2af81a99d5b12586471a56f344e4d5ed46822186170706c69636174696f6e2f782d6d73646f776e6c6f6164 
2017-10-13 12:36:27,198 ERROR    lbryum:116: [CoinChooserOldestFirst] change: [(1, 'bFE51kBH2vtWQxdujjrADkEFD5pJffNtzX', 21469000)]

2017-10-13 12:36:27,198 ERROR    lbryum:116: [CoinChooserOldestFirst] using 1 inputs

2017-10-13 12:36:27,198 ERROR    lbryum:116: [CoinChooserOldestFirst] using buckets: [u'c680b144b74aae9099e2fd810d7bacce843542a83d4cd851a2495083c6a6936f:1']

2017-10-13 12:36:27,454 ERROR    lbryum:116: adding signature for ff0488b21e000000000000000000772c0f4cd802aeeba55c5f8ede11d1577348c83a9291304da7c49385ab6220f4027bf125aff396481ef24e50623b18313e3036261a1d630d67656b8ef368afc7a201002501

2017-10-13 12:36:27,957 ERROR    lbryum:116: is_complete True

2017-10-13 12:36:28,220 INFO     lbrynet.core.Wallet:949: Saving metadata for claim 2aadf81fd28847f4fe6701c4b2d56674c8df2e98146c76fe063c71ed48c728d3 0
2017-10-13 12:36:36,019 INFO     lbrynet.daemon.Daemon:716: Success! Published to lbry://support1 txid: 2aadf81fd28847f4fe6701c4b2d56674c8df2e98146c76fe063c71ed48c728d3 nout: 0
2017-10-13 12:36:36,783 INFO     lbrynet.reflector.client.client:137: Reflector needs descriptor and 1 blobs for lbry://support1
2017-10-13 12:36:37,332 INFO     lbrynet.reflector.client.client:227: Sent reflector descriptor 5bec71ad464d86dd
2017-10-13 12:36:40,229 INFO     lbrynet.reflector.client.client:80: Reflector has all blobs for lbry://support1 (5bec71ad464d86dd)
2017-10-13 12:36:40,229 INFO     lbrynet.daemon.Daemon:712: Reflected new publication to lbry://support1
```
support added:
```
2017-10-13 12:43:18,933 ERROR    lbryum:116: [CoinChooserOldestFirst] change: [(1, 'bGDzAwtqrm3v6ppKvv6RoPwc8mhaL9f7gC', 297915900)]

2017-10-13 12:43:18,934 ERROR    lbryum:116: [CoinChooserOldestFirst] using 1 inputs

2017-10-13 12:43:18,934 ERROR    lbryum:116: [CoinChooserOldestFirst] using buckets: [u'56d1d619952fe56a6e99565853a3d9539e2b57c20f27000199da2fbc0a6f2d8b:1']

2017-10-13 12:43:19,151 ERROR    lbryum:116: adding signature for ff0488b21e000000000000000000772c0f4cd802aeeba55c5f8ede11d1577348c83a9291304da7c49385ab6220f4027bf125aff396481ef24e50623b18313e3036261a1d630d67656b8ef368afc7a201003301

2017-10-13 12:43:19,700 ERROR    lbryum:116: is_complete True

2017-10-13 12:43:19,815 INFO     lbrynet.core.Wallet:1408: Broadcast tx: 73ffbcb87b4e7548047c63d55ae91d8d44d7ef957603f2e174d791ca26680e52
```

editing:
```
2017-10-13 12:53:59,082 INFO     lbrynet.daemon.Daemon:1908: Publish: {'claim_address': None, 'name': u'support1', 'bid': 0.01, 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'source': {u'source': u'5bec71ad464d86ddf29d8858b9a159d2552bb8cd0d15eb1fa5aee64013c6e2af81a99d5b12586471a56f344e4d5ed468', u'version': u'_0_0_1', u'contentType': u'application/x-msdownload', u'sourceType': u'lbry_sd_hash'}, 'version': '_0_0_1', 'metadata': {u'description': u'original claim\n1st edit after adding a support', u'license': u'', u'title': u'support issue', u'language': u'en', 'version': '_0_1_0', u'nsfw': False, u'licenseUrl': None, u'thumbnail': u'https://spee.ch/6/lbrydropgif.gif'}}}, 'file_path': None, 'change_address': None}
2017-10-13 12:53:59,084 INFO     lbrynet.core.Wallet:1368: Send claim: support1 for 0.01: 080110011ac60108011270080410011a0d737570706f7274206973737565222e6f726967696e616c20636c61696d0a317374206564697420616674657220616464696e67206120737570706f72742a00320038004a2168747470733a2f2f737065652e63682f362f6c62727964726f706769662e67696652005a001a50080110011a305bec71ad464d86ddf29d8858b9a159d2552bb8cd0d15eb1fa5aee64013c6e2af81a99d5b12586471a56f344e4d5ed46822186170706c69636174696f6e2f782d6d73646f776e6c6f6164 
2017-10-13 12:54:06,621 ERROR    lbrynet.daemon.auth.server:353: Failed to process publish: Claim to name support1 failed: Cannot update a support
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
  File "site-packages\lbrynet\core\Wallet.py", line 945, in claim_name
Exception: Claim to name support1 failed: Cannot update a support

```

**Comment by tzarebczan** [comment]
This is no longer happening with the new wallet.
