### ISSUE TITLE
getnameclaims returns error when passing claim_id

### ISSUE THREAD

**Issue by hackrush01** [lbryio/lbryum#162]
Sometimes it works and sometimes it doesn't. (For working example see #161)

This
`lbryum getnameclaims --claim_id=2e821d91ffeb0cd100a3570753392d4b2116862d`
Returns
```shell
Traceback (most recent call last):
  File "/root/git-repos/lbry/lbry-venv/bin/lbryum", line 11, in <module>
    load_entry_point('lbryum', 'console_scripts', 'lbryum')()
  File "/root/git-repos/lbry-repos/lbryum/lbryum/main.py", line 273, in main
    result = server.run_cmdline(config_options)
  File "/root/git-repos/lbry/lbry-venv/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 288, in __call__
    return self.__send(self.__name, args)
  File "/root/git-repos/lbry/lbry-venv/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "/root/git-repos/lbry/lbry-venv/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u"<type 'exceptions.AttributeError'>:'Decimal' object has no attribute '__dict__'")
```

**Comment by jackrobison** [comment]
this has been fixed
