### ISSUE TITLE
Blockchain request timed out, daemon does not recover until restart

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbryum#165]
Bill posted this spee.ch issue a couple days ago on the team Slack.  The end result was the daemon not being able to publish/create channels due to network rules.  Looks like there was a blockchain timeout during a publish which started the problem.

```
2017-10-25 12:12:51,022 INFO     lbrynet.daemon.Daemon:1908: Publish: {'claim_address': u'banpwixPosfVDWnGvXqU2af36Qpsd7buGd', 'name': u'29052016-PORTOGR4', 'bid': 0.01, 'claim_dict': {'version': '_0_0_1', 'claimType': 'streamType', 'stream': {'version': '_0_0_1', 'metadata': {u'description': u'', u'license': u'Public Domain', u'author': u'spee.ch', u'title': u'29052016-PORTOGR4', u'language': u'en', 'version': '_0_1_0', u'nsfw': False}}}, 'file_path': u'/home/lbry/Downloads/29052016-PORTOGR4.jpg', 'change_address': None}
2017-10-25 12:13:05,503 INFO     lbrynet.daemon.Publisher:27: Starting publish for 29052016-PORTOGR4
2017-10-25 12:13:06,567 INFO     lbrynet.lbry_file.EncryptedFileMetadataManager:246: Saved sd blob hash be4a8a928b2dbb4a0ddaa91b691ce9b75af2217567c1db43ccdf5c43c45063867b3b88b9fafded60c577964ef88fc7b3 to stream hash 2cad6eb8b085ea2716c99789a5e4b11d519d166d2a8ed9b4293edd08e80a8ac532aaa64198b4f7488887100a9c306444
2017-10-25 12:13:06,570 INFO     lbrynet.core.Wallet:1368: Send claim: 29052016-PORTOGR4 for 0.01: 080110011a810108011239080410011a1132393035323031362d504f52544f47523422002a07737065652e6368320d5075626c696320446f6d61696e38004a0052005a001a42080110011a30be4a8a928b2dbb4a0ddaa91b691ce9b75af2217567c1db43ccdf5c43c45063867b3b88b9fafded60c577964ef88fc7b3220a696d6167652f6a706567 
2017-10-25 12:13:13,512 ERROR    lbryum.network:698: blockchain request timed out
2017-10-25 12:13:14,310 ERROR    lbryum:116: [CoinChooserOldestFirst] change: [(1, 'bDXadMe4zadBCCPkCc3TgjcdeqNNQF8CPM', 59516800)]

2017-10-25 12:13:14,310 ERROR    lbryum:116: [CoinChooserOldestFirst] using 1 inputs

2017-10-25 12:13:14,310 ERROR    lbryum:116: [CoinChooserOldestFirst] using buckets: [u'0c867d7997aa4936d9f23d23945b50bb738c5cc7b048c1144972a09b3f40e16e:1']

2017-10-25 12:13:14,526 ERROR    lbryum:116: adding signature for ff0488b21e000000000000000000bd65a3a5d0de7088b844ce8e0c8d766fdb05becbe2c7ae4f2688b2d61265f5da02da986b32ad2352e30a0039ad438c9e06c572ba149d5fa364dcaece6c7ab515d90100562c

2017-10-25 12:13:14,929 ERROR    lbryum:116: is_complete True

2017-10-25 12:13:14,930 ERROR    lbrynet.daemon.auth.server:353: Failed to process publish: Not connected.
Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
  File "site-packages/lbrynet/core/Wallet.py", line 1372, in _send_name_claim
  File "site-packages/lbrynet/core/Wallet.py", line 1288, in _run_cmd_as_defer_succeed
  File "site-packages/lbryum/commands.py", line 91, in func_wrapper
  File "site-packages/lbryum/commands.py", line 1689, in claim
  File "site-packages/lbryum/wallet.py", line 1214, in sendtx
  File "site-packages/lbryum/wallet.py", line 1222, in send_tx
AssertionError: Not connected.
2017-10-25 12:13:51,253 ERROR    lbryum.network:698: blockchain request timed out
2017-10-25 12:14:33,187 INFO     lbrynet.core.Wallet:823: Resolving 29052016-PORTOGR2#28d8d44f7fad0ec84724a181c9e47a89a4412079
2017-10-25 12:14:34,187 INFO     lbrynet.core.Wallet:823: Resolving 29052016-PORTOGR3#bd389aceebbfc58b5302cba3242ed7be5d155606
2017-10-25 12:14:35,189 INFO     lbrynet.core.Wallet:823: Resolving 29052016-PORTOGR1#1e605994cbbce948289a41ae3ba1c2729dbc16be
2017-10-25 12:14:36,187 INFO     lbrynet.core.Wallet:823: Resolving a-false-mirror-charles-todd-mobi#850baec0af66d766fcaaedf1531ac4f3519c6376
2017-10-25 12:14:51,205 ERROR    lbryum.network:698: blockchain request timed out

```

Transactions afterwards would result in this: 
```
2017-10-25 18:26:32,912 INFO     lbrynet.daemon.Publisher:27: Starting publish for get-out-of-here
2017-10-25 18:26:33,065 INFO     lbrynet.lbry_file.EncryptedFileMetadataManager:246: Saved sd blob hash efc0e11fb9c9207c2f5ef8826f7b55b1a141fc7c944142e7d5b946a6a9a57dac1e45c9ae5b1ab983d50ec1163db203c4 to stream hash 72988237174ee21026c4992b1019b8eecd394ea472a1a28751ce9fdc3b4df41b705d13d1775004558cabc2a1491364d7
2017-10-25 18:26:33,068 INFO     lbrynet.core.Wallet:1368: Send claim: get-out-of-here for 0.01: 080110011a7e08011237080410011a0f6765742d6f75742d6f662d6865726522002a07737065652e6368320d5075626c696320446f6d61696e38004a0052005a001a41080110011a30efc0e11fb9c9207c2f5ef8826f7b55b1a141fc7c944142e7d5b946a6a9a57dac1e45c9ae5b1ab983d50ec1163db203c42209696d6167652f676966 
2017-10-25 18:26:38,440 ERROR    lbryum:116: [CoinChooserOldestFirst] change: [(1, 'bKoHKmpz18K2fXsMuaNeoCRASJd5XpxHyu', 59521900)]

2017-10-25 18:26:38,442 ERROR    lbryum:116: [CoinChooserOldestFirst] using 1 inputs

2017-10-25 18:26:38,442 ERROR    lbryum:116: [CoinChooserOldestFirst] using buckets: [u'0c867d7997aa4936d9f23d23945b50bb738c5cc7b048c1144972a09b3f40e16e:1']

2017-10-25 18:26:39,133 ERROR    lbryum:116: adding signature for ff0488b21e000000000000000000bd65a3a5d0de7088b844ce8e0c8d766fdb05becbe2c7ae4f2688b2d61265f5da02da986b32ad2352e30a0039ad438c9e06c572ba149d5fa364dcaece6c7ab515d90100562c

2017-10-25 18:26:40,349 ERROR    lbryum:116: is_complete True

2017-10-25 18:26:40,475 ERROR    lbrynet.daemon.auth.server:353: Failed to process publish: Claim to name get-out-of-here failed: error: The transaction was rejected by network rules.(18: bad-txns-inputs-spent)
[01000000016ee1403f9ba0724914c148b0c75c8c73bb505b94233df2d93649aa97797d860c010000006b483045022100e859b3077b2960de38903df19b1458ee04bf9eb3619f7bc5be79f775e024211b02207cd89ede20a4370905eae2a5059bc985874c618b4fe66dbc32809eab1639e97d012102f6307f114727bec182d67d17e1d33e878066af1eb195dfc2b75f2e711d39c067ffffffff0240420f0000000000b2b50f6765742d6f75742d6f662d686572654c84080110011a7e08011237080410011a0f6765742d6f75742d6f662d6865726522002a07737065652e6368320d5075626c696320446f6d61696e38004a0052005a001a41080110011a30efc0e11fb9c9207c2f5ef8826f7b55b1a141fc7c944142e7d5b946a6a9a57dac1e45c9ae5b1ab983d50ec1163db203c42209696d6167652f6769666d7576a914f1feef9c44a91ed89ac8d8cc746523e3d18af3ec88ac6c3b8c03000000001976a9144d8b11fd73a90760a38354a8bc2466e0ee8020ff88ac00000000]
Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
  File "site-packages/lbrynet/core/Wallet.py", line 945, in claim_name
Exception: Claim to name get-out-of-here failed: error: The transaction was rejected by network rules.(18: bad-txns-inputs-spent)
[01000000016ee1403f9ba0724914c148b0c75c8c73bb505b94233df2d93649aa97797d860c010000006b483045022100e859b3077b2960de38903df19b1458ee04bf9eb3619f7bc5be79f775e024211b02207cd89ede20a4370905eae2a5059bc985874c618b4fe66dbc32809eab1639e97d012102f6307f114727bec182d67d17e1d33e878066af1eb195dfc2b75f2e711d39c067ffffffff0240420f0000000000b2b50f6765742d6f75742d6f662d686572654c84080110011a7e08011237080410011a0f6765742d6f75742d6f662d6865726522002a07737065652e6368320d5075626c696320446f6d61696e38004a0052005a001a41080110011a30efc0e11fb9c9207c2f5ef8826f7b55b1a141fc7c944142e7d5b946a6a9a57dac1e45c9ae5b1ab983d50ec1163db203c42209696d6167652f6769666d7576a914f1feef9c44a91ed89ac8d8

```

Longer log file here: [fulllog.txt](https://github.com/lbryio/lbryum/files/1428173/fulllog.txt)
cc746523e3d18af3ec88ac6c3b8c03000000001976a9144d8b11fd73a90760a38354a8bc2466e0ee8020ff88ac00000000]

**Comment by tzarebczan** [comment]
Something similar happened to be on my main machine - I can't run claim_list_mine or resolves (probably other blockchain related commands too) - they time out.  Still need to find out is this is related to lbry wallet bloat, but I still think the daemon should be able to recover from this somehow. 

```
c:\Program Files (x86)\LBRY\resources\app\dist>lbrynet-cli resolve ten
ERROR: Failed to get response from server within timeout of 30

```
```
2017-10-30 16:21:31,638 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:21:31,638 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:24:31,996 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:24:31,996 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:25:31,894 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:25:31,894 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:26:31,911 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:26:31,911 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:27:31,956 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:27:31,956 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:28:32,204 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:28:32,204 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:31:32,142 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:31:32,142 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:31:58,089 INFO     lbrynet.core.server.BlobRequestHandler:151: Sending 050f1c8ef767d359 to 91.125.166.152:56149
2017-10-30 16:33:32,611 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:33:32,611 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:34:32,427 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:34:32,427 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:36:32,523 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:36:32,523 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:39:32,592 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:39:32,592 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:41:32,739 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:41:32,739 ERROR    lbryum.network:698: blockchain request timed out
2017-10-30 16:42:55,492 INFO     lbrynet.core.server.BlobRequestHandler:151: Sending 5b61d8005d3799b4 to 85.0.35.178:62028
2017-10-30 16:43:02,710 INFO     lbrynet.core.server.BlobRequestHandler:151: Sending f6100f902e0b41b9 to 85.0.35.178:62041
2017-10-30 16:43:04,615 INFO     lbrynet.core.server.BlobRequestHandler:151: Sending 63d17a725a474e5f to 85.0.35.178:62041
```

**Comment by tzarebczan** [comment]
Even Franklin ran into the issue this morning:
```
2017-11-03 08:00:04,365 INFO     lbrynet.daemon.DaemonControl:70: Starting lbrynet-daemon from command line
2017-11-03 08:00:04,862 INFO     lbrynet.daemon.DaemonServer:66: Using non-authenticated API
2017-11-03 08:00:04,865 INFO     lbrynet.daemon.Daemon:243: Starting lbrynet-daemon
2017-11-03 08:00:04,878 INFO     lbrynet.daemon.ExchangeRateManager:210: Starting exchange rate manager
2017-11-03 08:00:05,282 INFO     lbrynet.daemon.Daemon:269: Platform: {"lbrynet_version": "0.17.2rc7", "platform": "Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial", "os_system": "Linux", "python_version": "2.7.12", "os_release": "4.4.0-93-generic", "lbryum_version": "3.1.11rc6", "ip": "54.173.171.189", "lbryschema_version": "0.0.14rc2", "processor": "x86_64", "build": "rc"}
2017-11-03 08:00:05,289 INFO     lbrynet.daemon.Daemon:479: Loading databases
2017-11-03 08:00:05,298 WARNING  lbrynet.daemon.Daemon:490: db_revision file not found. Creating it
2017-11-03 08:00:05,333 INFO     lbrynet.daemon.Daemon:509: Upgrading your databases
2017-11-03 08:00:05,350 INFO     lbrynet.db_migrator.migrate1to2:9: Doing the migration
2017-11-03 08:00:05,351 INFO     lbrynet.db_migrator.migrate1to2:11: Migration succeeded
2017-11-03 08:00:05,351 INFO     lbrynet.db_migrator.migrate2to3:9: Doing the migration
2017-11-03 08:00:05,351 INFO     lbrynet.db_migrator.migrate2to3:11: Migration succeeded
2017-11-03 08:00:05,352 INFO     lbrynet.db_migrator.migrate3to4:9: Doing the migration
2017-11-03 08:00:05,352 INFO     lbrynet.db_migrator.migrate3to4:11: Migration succeeded
2017-11-03 08:00:05,353 INFO     lbrynet.daemon.Daemon:505: Finished upgrading the databases.
2017-11-03 08:00:05,353 INFO     lbrynet.daemon.Daemon:545: Using lbryum wallet
2017-11-03 08:00:07,918 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:00:09,372 INFO     lbrynet.core.Session:254: Starting DHT
2017-11-03 08:00:09,420 INFO     lbrynet.dht.protocol:178: DHT listening on UDP 4444
2017-11-03 08:00:11,656 INFO     lbrynet.core.RateLimiter:72: Starting rate limiter.
2017-11-03 08:00:11,657 INFO     lbrynet.core.BlobManager:42: Starting disk blob manager. blob_dir: /home/lbry/.lbrynet/blobfiles, db_file: /home/lbry/.lbrynet/blobs.db
2017-11-03 08:00:11,658 INFO     lbrynet.core.Wallet:451: Starting wallet.
2017-11-03 08:00:11,704 INFO     lbrynet.core.Wallet:1170: Loading the wallet
2017-11-03 08:00:13,844 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:00:18,848 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:00:23,851 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:00:24,001 INFO     lbrynet.core.Wallet:1261: Local Height: 265901, remote height: 266389, behind: 488
2017-11-03 08:00:28,856 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:00:33,861 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:00:38,866 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:00:43,871 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:00:48,876 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:00:53,881 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:00:58,886 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:01:03,892 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:01:08,897 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:01:12,244 INFO     lbrynet.core.Wallet:1261: Local Height: 265901, remote height: 0, behind: None
2017-11-03 08:01:13,902 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:01:18,908 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:01:19,238 INFO     lbrynet.core.Wallet:1261: Local Height: 265901, remote height: 266389, behind: 488
2017-11-03 08:01:23,913 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:01:28,918 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:01:33,923 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:01:38,927 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:01:43,931 WARNING  lbrynet.daemon.auth.server:331: Function not allowed during startup: wallet_balance
2017-11-03 08:02:12,243 INFO     lbrynet.core.Wallet:1261: Local Height: 266015, remote height: 0, behind: None
2017-11-03 08:02:12,770 INFO     lbrynet.core.Wallet:1261: Local Height: 266015, remote height: 266389, behind: 374
2017-11-03 08:02:42,901 ERROR    lbryum.network:698: blockchain request timed out
2017-11-03 08:03:12,103 INFO     lbrynet.core.Wallet:1261: Local Height: 266015, remote height: 0, behind: None
2017-11-03 08:03:12,263 INFO     lbrynet.core.Wallet:1261: Local Height: 266015, remote height: 266389, behind: 374
2017-11-03 08:03:17,497 INFO     lbrynet.core.Wallet:1261: Local Height: 266015, remote height: 266389, behind: 374
2017-11-03 08:03:32,661 INFO     lbrynet.core.Wallet:1261: Local Height: 266389, remote height: 266389, behind: 0
2017-11-03 08:03:32,661 INFO     lbrynet.core.Wallet:1269: Wallet Loaded
2017-11-03 08:03:32,662 INFO     lbrynet.core.Wallet:1194: Subscribing to addresses
2017-11-03 08:03:32,762 INFO     lbrynet.core.Wallet:1196: Synchronized wallet
2017-11-03 08:03:32,783 INFO     lbrynet.core.BlobAvailability:30: Starting blob availability tracker.
2017-11-03 08:03:32,787 INFO     lbrynet.daemon.Daemon:518: Starting to setup up file manager
2017-11-03 08:03:32,820 INFO     lbrynet.file_manager.EncryptedFileManager:58: Started file manager
2017-11-03 08:03:32,821 INFO     lbrynet.daemon.Daemon:529: Done setting up file manager
2017-11-03 08:03:32,821 INFO     lbrynet.daemon.Daemon:303: Daemon bound to port: 3333
2017-11-03 08:03:32,822 INFO     lbrynet.daemon.Daemon:259: Starting balance: 8547.050317
2017-11-03 08:03:32,823 INFO     lbrynet.daemon.Daemon:237: Started lbrynet-daemon
2017-11-03 08:03:32,823 INFO     lbrynet.daemon.Daemon:238: 0 blobs in manager
2017-11-03 08:03:32,824 INFO     lbrynet.file_manager.EncryptedFileManager:125: Started 0 lbry files
2017-11-03 08:31:04,459 ERROR    lbryum.network:698: blockchain request timed out
2017-11-03 08:33:47,423 ERROR    lbryum.network:698: blockchain request timed out

```

**Comment by lyoshenka** [comment]
I've also been having issues with lbryum servers during publishing. Jack
said he restarted one last night. That seems to have  helped with my stuff.

**Comment by tzarebczan** [comment]
Still getting blockchain timeouts upon startup sometimes. Restarting fixes it.

**Comment by tzarebczan** [comment]
Theoretically, the daemon/wallet should be able to recover from a timeout and sync back up when the server is available.

**Comment by eukreign** [comment]
new wallet re-connects when connection is lost to lbryumx
