### ISSUE TITLE
transaction_list KeyError for transferred claim

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbryum#168]
I'm gonna have to go back and check the exact steps to reproduce this one, but I'm getting the below error on RC8. I'm pretty sure it's a claim that originally had a channel on 1 PC and was transferred to this machine which has the error. I also tried re-signing it afterward on a new channel, but it may be erroring on the original tx.

```
ERROR: '107270d4064f090d905ac29f5b720381fbb1ed57'

Help for transaction_list method:

        List transactions belonging to wallet

        Usage:
            transaction_list [-t]

        Options:
            -t  : Include claim tip information

        Returns:
            (list) List of transactions, where is_tip is null by default,
             and set to a boolean if include_tip_info is true

            {
                "claim_info": (list) claim info if in txn [{"amount": (float) claim amount,
                                                            "claim_id": (str) claim id,
                                                            "claim_name": (str) claim name,
                                                            "nout": (int) nout}],
                "confirmations": (int) number of confirmations for the txn,
                "date": (str) date and time of txn,
                "fee": (float) txn fee,
                "support_info": (list) support info if in txn [{"amount": (float) support amount,
                                                                "claim_id": (str) claim id,
                                                                "claim_name": (str) claim name,
                                                                "is_tip": (null) default,
                                                                (bool) if include_tip_info is true,
                                                                "nout": (int) nout}],
                "timestamp": (int) timestamp,
                "txid": (str) txn id,
                "update_info": (list) update info if in txn [{"amount": (float) updated amount,
                                                              "claim_id": (str) claim id,
                                                              "claim_name": (str) claim name,
                                                              "nout": (int) nout}],
                "value": (float) value of txn
            }


Here's the traceback for the error you encountered:
Traceback (most recent call last):
  File "site-packages\twisted\web\server.py", line 190, in process

  File "site-packages\twisted\web\server.py", line 241, in render

  File "site-packages\lbrynet\daemon\auth\server.py", line 249, in render

  File "site-packages\lbrynet\daemon\auth\server.py", line 368, in _render

--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 150, in maybeDeferred

  File "site-packages\lbrynet\daemon\Daemon.py", line 2198, in jsonrpc_transaction_list

  File "site-packages\lbrynet\core\Wallet.py", line 995, in get_history

  File "site-packages\lbrynet\core\Wallet.py", line 1477, in _get_history

  File "site-packages\lbrynet\core\Wallet.py", line 1288, in _run_cmd_as_defer_succeed

  File "site-packages\lbryum\commands.py", line 91, in func_wrapper

  File "site-packages\lbryum\commands.py", line 614, in tiphistory

  File "site-packages\lbryum\commands.py", line 91, in func_wrapper

  File "site-packages\lbryum\commands.py", line 594, in claimhistory

  File "site-packages\lbryum\commands.py", line 558, in get_info_dict

exceptions.KeyError: '107270d4064f090d905ac29f5b720381fbb1ed57'
```

**Comment by tzarebczan** [comment]
Can confirm this was fixed by https://github.com/lbryio/lbryum/pull/170
