### ISSUE TITLE
KeyError: 'supports' - when resolving lbry://what

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbryum#178]
## The Issue
When resolving lbry://what, the daemon throws a key error.

```
c:\Program Files (x86)\LBRY\resources\app\dist>lbrynet-cli resolve lbry://what#790cd199f4177a1b2045c0f2e5ed922ee4dbce29
ERROR: 'supports'

Here's the traceback for the error you encountered:
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 498, in errback

  File "site-packages\twisted\internet\defer.py", line 565, in _startRunCallbacks

  File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks

  File "site-packages\twisted\internet\defer.py", line 1355, in gotResult

--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks

  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator

  File "site-packages\lbrynet\daemon\Daemon.py", line 1494, in jsonrpc_resolve

  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks

  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator

  File "site-packages\lbrynet\core\Wallet.py", line 836, in resolve

  File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks

  File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator

  File "site-packages\lbrynet\core\Wallet.py", line 790, in _handle_claim_result

  File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks

  File "site-packages\lbrynet\core\Wallet.py", line 749, in _decode_and_cache_claim_result

exceptions.KeyError: 'supports'
```

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Per discussion with Jack, this has to do with expiring claims.

**Comment by lyoshenka** [comment]
jack says this will stop happening when claim caching is removed
