### ISSUE TITLE
KeyError: 'value' error claim_list_mine when claim has an abandoned channel

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbryum#193]
If you abandon a channel claim that still has content claims attached, this is the result (after a deamon restart):

```
2018-01-04 16:21:27,674 WARNING  lbryum.commands:1561: Fetching 2 certificate claims for claims made with certificates not in this wallet
2018-01-04 16:21:28,309 ERROR    lbrynet.daemon.auth.server:353: Failed to process claim_list_mine: 'value'
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
  File "site-packages\lbrynet\daemon\Daemon.py", line 2030, in jsonrpc_claim_list_mine
  File "site-packages\lbrynet\core\Wallet.py", line 1376, in get_name_claims
  File "site-packages\lbrynet\core\Wallet.py", line 1288, in _run_cmd_as_defer_succeed
  File "site-packages\lbryum\commands.py", line 91, in func_wrapper
  File "site-packages\lbryum\commands.py", line 1567, in getnameclaims
KeyError: 'value'
```

**Comment by tzarebczan** [comment]
Just had a user run into this. It also causes your Publishes area to stop loading since claim_list_mine fails.  

The workaround is to manually remove the claim that had the abandoned channel associated with it.

**Comment by tzarebczan** [comment]
@eukreign please keep this in mind when working on the new wallet.
