### ISSUE TITLE
exceptions.OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by whitslack** [lbryio/lbryum#4]
Exception occurred shortly after publishing a file using the `lbrynet-console` at commit 71c2cd50659eff76f784304cb633b253296c3506. Lbryum itself was at commit a6676c2f5ce3629dc58eb1d775b215f858bf0f13.

```
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/python/threadpool.py", line 196, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib64/python2.7/site-packages/lbryum/wallet.py", line 141, in write
    os.rename(temp_path, self.path)
exceptions.OSError: [Errno 2] No such file or directory
```

**Comment by whitslack** [comment]
This error occurred again, this time with `lbrynet-console` at commit `8db2e10696355cda1d0da6c42cd657169458cbb1` and lbryum still at commit a6676c2f5ce3629dc58eb1d775b215f858bf0f13.

However, this time, following the `No such file or directory` error, there was the following:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/site-packages/lbryum/network.py", line 767, in run
    self.wait_on_sockets()
  File "/usr/lib64/python2.7/site-packages/lbryum/network.py", line 761, in wait_on_sockets
    self.process_responses(interface)
  File "/usr/lib64/python2.7/site-packages/lbryum/network.py", line 552, in process_responses
    self.process_response(interface, response, callbacks)
  File "/usr/lib64/python2.7/site-packages/lbryum/network.py", line 501, in process_response
    self.on_get_header(interface, response)
  File "/usr/lib64/python2.7/site-packages/lbryum/network.py", line 702, in on_get_header
    interface.stop()
AttributeError: 'Interface' object has no attribute 'stop'
```

**Comment by jackrobison** [comment]
This one is really old, and doesn't happen any more. `lbrynet-console` has also been deprecated.
